import { Property } from "@/types/Properties";

export const mockPropertyDetails: Property[] = [
  {
    id: "1",
    title: "Modern Villa in Gacuriro",
    type: "house",
    category: "sale",
    price: 200000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 900,
    location: "Gacuriro, Kigali",
    featured: true,
    description:
      "Luxurious modern villa with panoramic city views, private pool, and smart home technology. This stunning property features high-end finishes throughout, an open-concept living area, and a gourmet kitchen perfect for entertaining. The master suite includes a walk-in closet and spa-like bathroom.",
    features: [
      "Private Swimming Pool",
      "Smart Home Technology",
      "Panoramic City Views",
      "Gourmet Kitchen",
      "Master Suite with Walk-in Closet",
      "Private Garden",
      "2-Car Garage",
      "24/7 Security System",
    ],

    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922340/ID26711-Image_1_aykc3v.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017159/20230301_133532_bra5eb.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017119/8d576cfe-f530-4457-b2f4-639dc4087833_4_HF8_4_xcix7m.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017066/Kishani_20Perera_Point_20Dume_20Project_Photographer_20Anthony_20Barcelo_cxobwk.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017004/BiancoMarble2424_BlackHexagon_Freestanding-tub-feeee865_bxoipv.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017193/1200px-Backyardpool_iuecg9.jpg",
    ],
    roomTypes: [
      "Exterior View",
      "Living Room",
      "Modern Kitchen",
      "Master Bedroom",
      "Bathroom",
      "Pool Area",
    ],
  },
  {
    id: "2",
    title: "Luxury Apartment for Rent",
    type: "house",
    category: "rent",
    price: 750000,
    bedrooms: 2,
    bathrooms: 2,
    area: 450,
    location: "Downtown, Kigali",
    featured: true,
    description:
      "Stylish downtown apartment with high-end finishes and convenient access to entertainment. Features floor-to-ceiling windows, modern appliances, and stunning city views. Perfect for professionals seeking luxury urban living.",
    features: [
      "Floor-to-ceiling Windows",
      "City Views",
      "Modern Appliances",
      "Hardwood Floors",
      "In-unit Laundry",
      "Private Balcony",
      "Gym Access",
      "24/7 Concierge",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922339/prefab_home_in_burlingame_ca_2_480x480_eow7td.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017159/20230301_133532_bra5eb.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017119/8d576cfe-f530-4457-b2f4-639dc4087833_4_HF8_4_xcix7m.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017066/Kishani_20Perera_Point_20Dume_20Project_Photographer_20Anthony_20Barcelo_cxobwk.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017004/BiancoMarble2424_BlackHexagon_Freestanding-tub-feeee865_bxoipv.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017193/1200px-Backyardpool_iuecg9.jpg",
    ],
    roomTypes: [
      "Building Exterior",
      "Living Room",
      "Kitchen",
      "Bedroom",
      "Bathroom",
      "Pool Area",
    ],
  },
  {
    id: "3",
    title: "Commercial Plot for Development",
    type: "plot",
    category: "sale",
    price: 48000000,
    area: 800,
    location: "Kanombe, Kigali",
    featured: false,
    description:
      "Prime commercial land ready for development in growing business district. Ideal for retail, office, or mixed-use development with excellent visibility and accessibility. All utilities available and ready for immediate development.",
    features: [
      "Prime Commercial Location",
      "High Traffic Area",
      "All Utilities Available",
      "Zoned for Commercial Use",
      "Corner Lot Position",
      "Public Transportation Access",
      "Ample Parking Space",
      "Rapid Growth Area",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922608/39638198283_31e732cb49_b_raavo8.jpg",
    ],
    roomTypes: [
      "Aerial View",
      "Street View",
      "Access Road",
      "Surrounding Area",
    ],
  },
  {
    id: "4",
    title: "Suburban Family Home",
    type: "house",
    category: "sale",
    price: 31000000,
    bedrooms: 3,
    bathrooms: 2,
    area: 340,
    location: "Kimironko, Kigali",
    featured: true,
    description:
      "Luxurious modern villa with panoramic city views, private pool, and smart home technology. This stunning property features high-end finishes throughout, an open-concept living area, and a gourmet kitchen perfect for entertaining. The master suite includes a walk-in closet and spa-like bathroom.",

    features: [
      "Private Swimming Pool",
      "Smart Home Technology",
      "Panoramic City Views",
      "Gourmet Kitchen",
      "Master Suite with Walk-in Closet",
      "Private Garden",
      "2-Car Garage",
      "24/7 Security System",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922340/strategies-for-finding-cheap-houses-c81cd7_qh0hoh.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017159/20230301_133532_bra5eb.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017119/8d576cfe-f530-4457-b2f4-639dc4087833_4_HF8_4_xcix7m.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017066/Kishani_20Perera_Point_20Dume_20Project_Photographer_20Anthony_20Barcelo_cxobwk.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017004/BiancoMarble2424_BlackHexagon_Freestanding-tub-feeee865_bxoipv.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017193/1200px-Backyardpool_iuecg9.jpg",
    ],
    roomTypes: [
      "Exterior View",
      "Living Room",
      "Modern Kitchen",
      "Master Bedroom",
      "Bathroom",
      "Pool Area",
    ],
  },
  {
    id: "5",
    title: "Waterfront Luxury Condo",
    type: "house",
    category: "rent",
    price: 500000,
    bedrooms: 3,
    bathrooms: 3,
    area: 400,
    location: "Kicukiro, Kigali",
    featured: true,
    description:
      "Stylish downtown apartment with high-end finishes and convenient access to entertainment. Features floor-to-ceiling windows, modern appliances, and stunning city views. Perfect for professionals seeking luxury urban living.",

    features: [
      "Floor-to-ceiling Windows",
      "City Views",
      "Modern Appliances",
      "Hardwood Floors",
      "In-unit Laundry",
      "Private Balcony",
      "Gym Access",
      "24/7 Concierge",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922340/edc100123egan-002-6500742f5feb7.jpg_zwjtwf.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017159/20230301_133532_bra5eb.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017119/8d576cfe-f530-4457-b2f4-639dc4087833_4_HF8_4_xcix7m.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017066/Kishani_20Perera_Point_20Dume_20Project_Photographer_20Anthony_20Barcelo_cxobwk.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017004/BiancoMarble2424_BlackHexagon_Freestanding-tub-feeee865_bxoipv.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017193/1200px-Backyardpool_iuecg9.jpg",
    ],
    roomTypes: [
      "Building Exterior",
      "Living Room",
      "Kitchen",
      "Bedroom",
      "Bathroom",
      "Pool Area",
    ],
  },
  {
    id: "6",
    title: "Residential Village",
    type: "house",
    category: "sale",
    price: 95000000,
    bedrooms: 2,
    bathrooms: 2,
    area: 610,
    location: "Ruyenzi, Kamonyi",
    featured: false,
    description:
      "Prime commercial land ready for development in growing business district. Ideal for retail, office, or mixed-use development with excellent visibility and accessibility. All utilities available and ready for immediate development.",
    features: [
      "Prime Commercial Location",
      "High Traffic Area",
      "All Utilities Available",
      "Zoned for Commercial Use",
      "Corner Lot Position",
      "Public Transportation Access",
      "Ample Parking Space",
      "Rapid Growth Area",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922338/Homes_Average-House-Price-in-Every-State_nckpd2.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017159/20230301_133532_bra5eb.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017119/8d576cfe-f530-4457-b2f4-639dc4087833_4_HF8_4_xcix7m.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017066/Kishani_20Perera_Point_20Dume_20Project_Photographer_20Anthony_20Barcelo_cxobwk.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017004/BiancoMarble2424_BlackHexagon_Freestanding-tub-feeee865_bxoipv.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017193/1200px-Backyardpool_iuecg9.jpg",
    ],
    roomTypes: [
      "Aerial View",
      "Street View",
      "Access Road",
      "Surrounding Area",
    ],
  },
  {
    id: "7",
    title: "Residential Recreation Center",
    type: "house",
    category: "rent",
    price: 200000,
    bedrooms: 3,
    bathrooms: 3,
    area: 380,
    location: "Kagugu, Kigali",
    featured: true,
    description:
      "Luxurious modern villa with panoramic city views, private pool, and smart home technology. This stunning property features high-end finishes throughout, an open-concept living area, and a gourmet kitchen perfect for entertaining. The master suite includes a walk-in closet and spa-like bathroom.",
    features: [
      "Private Swimming Pool",
      "Smart Home Technology",
      "Panoramic City Views",
      "Gourmet Kitchen",
      "Master Suite with Walk-in Closet",
      "Private Garden",
      "2-Car Garage",
      "24/7 Security System",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922338/9024-Main-Image_1600x_lredub.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017159/20230301_133532_bra5eb.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017119/8d576cfe-f530-4457-b2f4-639dc4087833_4_HF8_4_xcix7m.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017066/Kishani_20Perera_Point_20Dume_20Project_Photographer_20Anthony_20Barcelo_cxobwk.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017004/BiancoMarble2424_BlackHexagon_Freestanding-tub-feeee865_bxoipv.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017193/1200px-Backyardpool_iuecg9.jpg",
    ],
    roomTypes: [
      "Exterior View",
      "Living Room",
      "Modern Kitchen",
      "Master Bedroom",
      "Bathroom",
      "Pool Area",
    ],
  },
  {
    id: "8",
    title: "Plot for Sale",
    type: "plot",
    category: "sale",
    price: 84000000,
    area: 1090,
    location: "Masaka, Kigali",
    featured: true,
    description:
      "Stylish downtown apartment with high-end finishes and convenient access to entertainment. Features floor-to-ceiling windows, modern appliances, and stunning city views. Perfect for professionals seeking luxury urban living.",
    features: [
      "Floor-to-ceiling Windows",
      "City Views",
      "Modern Appliances",
      "Hardwood Floors",
      "In-unit Laundry",
      "Private Balcony",
      "Gym Access",
      "24/7 Concierge",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922607/empty-field_r5g5vh.jpg",
    ],
    roomTypes: [
      "Building Exterior",
      "Living Room",
      "Kitchen",
      "Bedroom",
      "Bathroom",
      "Pool Area",
    ],
  },
  {
    id: "9",
    title: "Vision city",
    type: "house",
    category: "rent",
    price: 1200000,
    bedrooms: 3,
    bathrooms: 2,
    area: 280,
    location: "Kigali",
    featured: false,
    description:
      "Prime commercial land ready for development in growing business district. Ideal for retail, office, or mixed-use development with excellent visibility and accessibility. All utilities available and ready for immediate development.",
    features: [
      "Prime Commercial Location",
      "High Traffic Area",
      "All Utilities Available",
      "Zoned for Commercial Use",
      "Corner Lot Position",
      "Public Transportation Access",
      "Ample Parking Space",
      "Rapid Growth Area",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922339/craftsman-exterior_msrjon.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017159/20230301_133532_bra5eb.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017119/8d576cfe-f530-4457-b2f4-639dc4087833_4_HF8_4_xcix7m.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017066/Kishani_20Perera_Point_20Dume_20Project_Photographer_20Anthony_20Barcelo_cxobwk.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017004/BiancoMarble2424_BlackHexagon_Freestanding-tub-feeee865_bxoipv.jpg",
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1757017193/1200px-Backyardpool_iuecg9.jpg",
    ],
    roomTypes: [
      "Building Exterior",
      "Living Room",
      "Kitchen",
      "Bedroom",
      "Bathroom",
      "Pool Area",
    ],
  },
  {
    id: "10",
    title: "Business center plot for Sale",
    type: "plot",
    category: "sale",
    price: 60000000,
    area: 1200,
    location: "Kabuga, Kigali",
    featured: false,
    description:
      "Prime commercial land ready for development in growing business district. Ideal for retail, office, or mixed-use development with excellent visibility and accessibility. All utilities available and ready for immediate development.",
    features: [
      "Prime Commercial Location",
      "High Traffic Area",
      "All Utilities Available",
      "Zoned for Commercial Use",
      "Corner Lot Position",
      "Public Transportation Access",
      "Ample Parking Space",
      "Rapid Growth Area",
    ],
    image: "",
    images: [
      "https://res.cloudinary.com/dx2czuzzs/image/upload/v1756922608/https_3A_2F_2Fcloudfront-us-east-1.images.arcpublishing.com_2Fsltrib_2FLOPF5XPO4RGBNNXZ2JZIX4BXLY_gcvqzq.jpg",
    ],
    roomTypes: [
      "Aerial View",
      "Street View",
      "Access Road",
      "Surrounding Area",
    ],
  },
];
