import { Property } from "@/types/Properties";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Villa in Gacuriro",
    type: "house",
    category: "sale",
    price: 200000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 900,
    location: "Gacuriro, Kigali",
    image: "/house-6.webp",
    // featured: true,
    description:
      "Luxurious modern villa with panoramic city views, private pool, and smart home technology.",
  },
  {
    id: "2",
    title: "Luxury Apartment for Rent",
    type: "house",
    category: "rent",
    price: 750000,
    bedrooms: 2,
    bathrooms: 2,
    area: 450,
    location: "Downtown, Kigali",
    image: "/apartment3.webp",
    // featured: true,
    description:
      "Stylish downtown apartment with high-end finishes and convenient access to entertainment.",
  },
  {
    id: "3",
    title: "Commercial Plot for Development",
    type: "plot",
    category: "sale",
    price: 48000000,
    area: 800,
    location: "Kanombe, Kigali",
    image: "/plot.webp",
    // featured: false,
    description:
      "Prime commercial land ready for development in growing business district.",
  },
  {
    id: "4",
    title: "Suburban Family Home",
    type: "house",
    category: "sale",
    price: 31000000,
    bedrooms: 3,
    bathrooms: 2,
    area: 340,
    location: "Kimironko, Kigali",
    image: "/house5.webp",
    // featured: false,
    description:
      "Spacious family home in quiet neighborhood with excellent schools nearby.",
  },
  {
    id: "5",
    title: "Waterfront Luxury Condo",
    type: "house",
    category: "rent",
    price: 500000,
    bedrooms: 3,
    bathrooms: 3,
    area: 400,
    location: "Kicukiro, Kigali",
    image: "/house4.webp",
    // featured: true,
    description:
      "Stunning waterfront condo with private dock and panoramic ocean views.",
  },
  {
    id: "6",
    title: "Residential Village",
    type: "house",
    category: "sale",
    price: 95000000,
    area: 610,
    location: "Ruyenzi, Kamonyi",
    image: "house4.webp",
    // featured: true,
    description: "Nice house in a quiet neighborhood with easy freeway access.",
  },
  {
    id: "7",
    title: "Residential Recreation Center",
    type: "house",
    category: "rent",
    price: 200000,
    area: 380,
    location: "Kagugu, Kigali",
    image: "/apartment.webp",
    // featured: false,
    description: "Quiet neighborhood near roadway.",
  },
  {
    id: "8",
    title: "Plot for Sale",
    type: "plot",
    category: "sale",
    price: 84000000,
    area: 1090,
    location: "Masaka, Kigali",
    image: "house7.webp",
    // featured: false,
    description:
      "Large parcel zoned for residential development with easy freeway access.",
  },
  {
    id: "9",
    title: "Vision city",
    type: "house",
    category: "rent",
    price: 1200000,
    area: 280,
    location: "Kigali",
    image: "house.webp",
    // featured: false,
    description:
      "Luxurious modern villa with panoramic city views, private pool, and smart home technology.",
  },
  {
    id: "10",
    title: "Business center plot for Sale",
    type: "plot",
    category: "sale",
    price: 60000000,
    area: 12100,
    location: "Kabuga, Kigali",
    image: "plot2.webp",
    // featured: false,
    description: "Business plot with easy freeway access.",
  },
];
