export const {
  NEXTAUTH_URL,
  NEXTAUTH_SECRET,
  NEXTAUTH_DEBUG,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  MONGODB_URI,
  ADMIN_EMAIL,
  MAILERSEND_API_TOKEN,
  MAILERSEND_FROM_EMAIL,
  MAILERSEND_FROM_NAME,
  MAILERSEND_TO_EMAIL,
} = process.env;
